---
- name: Set Custom BASH Profile
  blockinfile:
    path: "/home/{{ ansible_env.SUDO_USER }}/.bashrc"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
    backup: yes
    insertafter: EOF
    marker_begin: "\n\n##### CUSTOM BASH PROFILE #####\n"
    marker_end: ""
    marker: "{mark}"
    block: |
      #GENERAL
      export EDITOR="vim"

      #PS1
      export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;90m\]➜  \[\033[01;34m\]\w\[\033[00m\]\[\033[01;33m\]\$(__git_ps1)\[\033[00m\] "

      #HISTORY
      export HISTTIMEFORMAT='%Y-%m-%d %T  '
      export HISTSIZE=10000
      export HISTFILESIZE=10000

      #MANPAGE THEME
      export LESS_TERMCAP_mb=$'\e[1;31m'     
      export LESS_TERMCAP_md=$'\e[1;33m'     
      export LESS_TERMCAP_so=$'\e[01;44;37m' 
      export LESS_TERMCAP_us=$'\e[01;37m'    
      export LESS_TERMCAP_me=$'\e[0m'        
      export LESS_TERMCAP_se=$'\e[0m'        
      export LESS_TERMCAP_ue=$'\e[0m'        
      export GROFF_NO_SGR=1

      #ALIAS
      alias pbcopy='xclip -selection clipboard' #Depends xclip package
      alias pbpaste='xclip -selection clipboard -o' #Depends xclip package
      alias ssh='ssh -o ServerAliveInterval=15'
      alias crontab='VISUAL=vi crontab'
      alias git='LANG="en_US" git'
      alias getIP='dig @8.8.8.8 +short'
      alias publicIP='curl ifconfig.so'
      alias infoIP='curl ipinfo.io/'

      #FUNCTIONS
      ss() { /bin/ss $@ | column -t ;}

      #TMUX
      t3() { tmux new-session\; split-window -v -p 66\; split-window -v\; select-pane -t0 ;}

      t4()
      {
        tmux new-session \; split-window -v -p 50\; split-window -h\; select-pane -t0\; split-window -h\; select-pane -t0
      }

  tags: bashrc

- name: Add Custom ZSH Themes
  blockinfile:
    path: "/home/{{ ansible_env.SUDO_USER }}/.zshrc"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
    backup: yes
    insertafter: '^ZSH_THEME.*'
    marker_begin: "##### CUSTOM ZSH THEMES #####"
    marker_end: ""
    marker: "{mark}"
    block: |
      #ZSH_THEME="bira"
      #ZSH_THEME="pygmalion"
      #ZSH_THEME="agnoster"
      #ZSH_THEME="miloshadzic"
      #ZSH_THEME="powerlevel9k/powerlevel9k"
      #ZSH_THEME="gnzh"
      #ZSH_THEME="lambda"
  tags: zshrc

- name: Set Custom ZSH Profile
  blockinfile:
    path: "/home/{{ ansible_env.SUDO_USER }}/.zshrc"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
    backup: yes
    insertafter: EOF
    marker_begin: "\n\n##### CUSTOM ZSH PROFILE #####\n"
    marker_end: ""
    marker: "{mark}"
    block: |
      #GENERAL
      export EDITOR="vim"

      #HISTORY
      alias history='history -i'
      HISTSIZE=10000
      SAVEHIST=10000
      HISTFILE=~/.zhistory

      #MANPAGE THEME
      export LESS_TERMCAP_mb=$'\e[1;31m'     
      export LESS_TERMCAP_md=$'\e[1;33m'     
      export LESS_TERMCAP_so=$'\e[01;44;37m' 
      export LESS_TERMCAP_us=$'\e[01;37m'    
      export LESS_TERMCAP_me=$'\e[0m'        
      export LESS_TERMCAP_se=$'\e[0m'        
      export LESS_TERMCAP_ue=$'\e[0m'        
      export GROFF_NO_SGR=1

      #ALIAS
      alias pbcopy='xclip -selection clipboard' #Depends xclip package
      alias pbpaste='xclip -selection clipboard -o' #Depends xclip package
      alias ssh='ssh -o ServerAliveInterval=15'
      alias crontab='VISUAL=vi crontab'
      alias git='LANG="en_US" git'
      alias getIP='dig @8.8.8.8 +short'
      alias publicIP='curl ifconfig.so'
      alias infoIP='curl ipinfo.io/'

      #FUNCTIONS
      ss() { /bin/ss $@ | column -t ;}

      #TMUX
      t3() { tmux new-session\; split-window -v -p 66\; split-window -v\; select-pane -t0 ;}

      t4()
      {
        tmux new-session \; split-window -v -p 50\; split-window -h\; select-pane -t0\; split-window -h\; select-pane -t0
      }

  tags: zshrc

- name: Copy .vimrc and .tmux.conf to Home Directory
  copy:
    src: "./{{ item }}"
    dest: "/home/{{ ansible_env.SUDO_USER }}/{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop:
    - .tmux.conf
    - .vimrc

- name: Create Wallpaper Directory 
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Copy Pictures to ~/Imagens/Wallpapers
  copy:
    src: "./{{ item }}"
    dest: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop:
    - root_2560x1080.png
    - root_1920x1080.png

- name: Set Default Wallpaper
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
  loop: "{{ wallpaper }}"
  tags: install_themes
  
