---
- name: Copy Custom Config Files to Home Directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ config_files }}"

- name: Create Wallpaper Directory 
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755
    state: directory

- name: Copy Pictures to ~/Imagens/Wallpapers
  copy:
    src: root.png
    dest: "/home/{{ ansible_env.SUDO_USER }}/Imagens/Wallpapers/root.png"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644

- name: Set Default Wallpaper
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
  loop: "{{ wallpaper }}"

- name: Set vim as Default Editor
  lineinfile:
    path: /etc/environment
    line: "EDITOR=vim"
    state: present