---

- name: Add Custom Config in .zshrc and .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
    backup: yes
    insertafter: EOF
    marker_begin: "##### CUSTOM CONFIG #####"
    marker_end: ""
    marker: "{mark}"
    block: |

      #GENERAL
      export EDITOR='vim'
      export HISTTIMEFORMAT='%Y/%m/%d %T  '
      export HISTSIZE=10000
      export HISTFILESIZE=20000

      #Manpage Theme
      export LESS_TERMCAP_mb=$'\e[1;31m'     
      export LESS_TERMCAP_md=$'\e[1;33m'     
      export LESS_TERMCAP_so=$'\e[01;44;37m' 
      export LESS_TERMCAP_us=$'\e[01;37m'    
      export LESS_TERMCAP_me=$'\e[0m'        
      export LESS_TERMCAP_se=$'\e[0m'        
      export LESS_TERMCAP_ue=$'\e[0m'        
      export GROFF_NO_SGR=1

      #ALIAS
      alias pbcopy='xclip -selection clipboard' #Depends xclip package
      alias pbpaste='xclip -selection clipboard -o' #Depends xclip package
      alias ssh='ssh -o ServerAliveInterval=15'
      alias crontab="VISUAL=vi crontab"
      alias git='LANG="en_US" git'

      #FUNCTIONS
      #TMUX
      t3()
      {
        tmux new-session\; split-window -v -p 66\; split-window -v\; select-pane -t0
      }

      t4()
      {
        tmux new-session \; split-window -v -p 50\; split-window -h\; select-pane -t0\; split-window -h\; select-pane -t0
      }

      ss() { /bin/ss $@ | column -t ;}

  loop: "{{ shell_cfg }}"
  tags: config_files

- name: Copy Config Files .vimrc and .tmux.conf to HOME
  copy:
    src: "./{{ item }}"
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ file_cfg }}"
  tags: config_files

- name: Copy Pictures to ~/Imagens/Wallpapers
  copy:
    src: "./{{ item }}"
    dest: "{{ ansible_env.HOME }}/Imagens/Wallpapers/{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
  loop: "{{ pics }}"

- name: Reboot Machine
  shell: shutdown -r +0
  
