---
# vars file for install

apt_key_urls:
  - https://dl.google.com/linux/linux_signing_key.pub #GoogleChrome
  - https://www.virtualbox.org/download/oracle_vbox_2016.asc #VirtualBox
  - https://apt.releases.hashicorp.com/gpg
 
apt_repo_urls:
  - url: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main #GoogleChrome
    filename: google-chrome
  - url: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib #VirtualBox
    filename: virtualbox
  - url: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main #Hashicorp
    filename: hashicorp

pkgs_urls:
  - "{{ url_deb_etcher.stdout }}" #BalenaEtcher

pkgs:
  - build-essential
  - calibre
  - celluloid
  - curl
  - google-chrome-stable
  - gparted
  - handbrake
  - htop
  - imagemagick
  - jq
  - lm-sensors
  - openssh-server
  - p7zip-full
  - p7zip-rar
  - peek
  - qbittorrent
  - scrcpy
  - steam
  - terraform
  - tmux
  - uget
  - vagrant
  - vim
  - virtualbox-6.1
  - xclip
  - zsh