--- 
- name: Get Balena Etcher Package Latest Version URL
  shell: >-
    curl -s "https://api.github.com/repos/balena-io/etcher/releases/latest" | egrep -o 'https.*amd64.deb'
  register: url_deb_etcher
  args:
    warn: false